# Generated by Django 4.2.6 on 2023-10-15 21:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("HS", "Hostel"),
                            ("HO", "Hotel"),
                            ("BB", "Bed & Breakfast"),
                            ("CS", "Campsite"),
                            ("AP", "Apartment"),
                        ],
                        max_length=10,
                        verbose_name="Property Type",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=64, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="State/Province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal Code"),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="phone",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "legal_entity",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legal Entity"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=200, verbose_name="Tax ID"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
                "ordering": ["-created"],
            },
        ),
    ]
