# Generated by Django 4.2.6 on 2023-10-18 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="num_of_guests",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Number of Guests",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="weekend_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Weekend Price",
            ),
        ),
    ]
