# Generated by Django 4.2.6 on 2023-10-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_room_num_of_guests_alter_room_weekend_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="weekday_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Weekday Price"
            ),
        ),
    ]
