# Generated by Django 4.2.6 on 2023-10-25 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_alter_room_weekday_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="weekday_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Weekday Price",
            ),
        ),
        migrations.CreateModel(
            name="Addon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=64, verbose_name="icon"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "addon",
                "verbose_name_plural": "addons",
            },
        ),
    ]
