# Generated by Django 4.2.6 on 2023-10-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_addon_alter_room_weekday_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
