# Generated by Django 4.2.6 on 2023-10-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_alter_room_weekday_price_addon"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="room",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
