# Generated by Django 4.2.6 on 2023-11-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_property_active_room_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Rate"
                    ),
                ),
                (
                    "availability",
                    models.PositiveIntegerField(default=1, verbose_name="Availability"),
                ),
                ("for_date", models.DateField(verbose_name="For Date")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="properties.room",
                        verbose_name="Occurrence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occurrence",
                "verbose_name_plural": "Occurrences",
            },
        ),
    ]
