# Generated by Django 4.2.6 on 2023-11-05 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_alter_occurrence_options_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ("property", "room_type"),
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
    ]
