# Generated by Django 4.2.6 on 2023-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0011_alter_room_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addon",
            options={
                "ordering": ("name",),
                "verbose_name": "Addon",
                "verbose_name_plural": "Addons",
            },
        ),
        migrations.AddConstraint(
            model_name="addon",
            constraint=models.UniqueConstraint(
                fields=("property", "name"), name="unique_addon"
            ),
        ),
    ]
