# Generated by Django 4.2.6 on 2023-11-11 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_alter_addon_options_addon_unique_addon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
    ]
